### PR TITLE
Add iflight f411 rx target

### PR DESCRIPTION
**Pull request by hallucino**
New bord: iflight f411 rx

I can't find the name of the board IFLIGHTF411RX in https://github.com/betaflight/unified-targets

[BTFL_cli_Baby_Nazgul 73_20211026_145412.txt](https://github.com/BossHobby/QUICKSILVER/files/7513300/BTFL_cli_Baby_Nazgul.73_20211026_145412.txt)

### CODE REVIEW

**Comment by bkleiner** [comment]
indeed there does not seem to be a matching unified target for this board...not the best performance on iflights part.

**Comment by bkleiner** [comment]
support for the CC2500_LNA_EN_PIN situation landed

**Comment by hallucino** [comment]
> support for the CC2500_LNA_EN_PIN situation landed

What do you mean ?

**Comment by bkleiner** [comment]
> we currently do no support USE_CC2500_PA_LNA without a CC2500_LNA_EN_PIN, however this is easy enough to add. please remove CC2500_LNA_EN_PIN

I pushed a [change to the firmware](https://github.com/BossHobby/QUICKSILVER/commit/e169fe8c375b5de07ee1243cf4b830408edf9e9a) to make it possible have the above situation work correctly - so once you remove `CC2500_ANT_SEL_PIN`, `USE_CC2500_DIVERSITY` and `CC2500_LNA_EN_PIN` we should be good to go.

**Comment by hallucino** [comment]
Is it good now ?

**Pull request merged**
